[package]
name = "panel"
version = "0.1.0"
authors = ["Ramiz Bahrami <ramesbahrami@gmail.com>", "Adrian MÃ¼ller <adrian@mueller-lindenfels.de>"]

[dependencies]
mio = { git = "https://github.com/carllerche/mio" }
time = "0.1"
